### ISSUE TITLE
Docspec 2.0.0 checklist

### ISSUE THREAD

**Issue by NiklasRosenstein** [NiklasRosenstein/docspec#61]
* [x] #54 
* [x] #49
* [x] Remove deprecated `ReverseMap` class
* [x] Support `pathlib.Path` as argument types where filesystem paths are expected
* [ ] https://github.com/NiklasRosenstein/docspec/issues/2
* [ ] https://github.com/NiklasRosenstein/docspec/issues/1
* [x] #65
* [ ] #66 
* [x] #67

This list may grow still.

**Comment by NiklasRosenstein** [comment]
https://github.com/NiklasRosenstein/docspec/pull/64

**Comment by NiklasRosenstein** [comment]
The items unchecked above are queued for 2.1.0
